name = "zamonwa"
compatibility_date = "2024-01-01"

[build]
command = "npm install --legacy-peer-deps && npm run build"
output_dir = "dist"

[site]
bucket = "./dist"

[pages]
build_output_directory = "dist"

[[r2_buckets]]
binding = "ARTWORK_BUCKET"
bucket_name = "zamonwa-artwork"