name = "zamonwa"
compatibility_date = "2024-01-01"

# Pages specific config
[pages]
build_output_directory = "dist"

# Optional: For R2 integration
[[pages.r2_buckets]]
binding = "ARTWORK_BUCKET"
bucket_name = "zamonwa-artwork"
preview_bucket_name = "zamonwa-artwork-preview"

[build]
command = "npm install && npm run build"